# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hello-nbdev',
                'doc_host': 'https://p-i-.github.io',
                'git_url': 'https://github.com/p-i-/hello-nbdev',
                'lib_path': 'hello_nbdev'},
  'syms': { 'hello_nbdev.hello': { 'hello_nbdev.hello.foo': ('hello.html#foo', 'hello_nbdev/hello.py'),
                                   'hello_nbdev.hello.say_hello': ('hello.html#say_hello', 'hello_nbdev/hello.py')}}}
