# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hello-nbdev',
                'doc_host': 'https://p-i-.github.io',
                'git_url': 'https://github.com/p-i-/hello-nbdev',
                'lib_path': 'hello_nbdev'},
  'syms': {'hello_nbdev.core': {'hello_nbdev.core.foo': ('core.html#foo', 'hello_nbdev/core.py')}}}
